# Generated by Django 4.2 on 2023-06-11 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0029_feedetails_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='Registered',
            field=models.BooleanField(default=False),
        ),
    ]
