# Generated by Django 4.2 on 2023-06-11 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0030_student_active_student_registered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Registered',
            field=models.BooleanField(default=True),
        ),
    ]
