# Generated by Django 4.2 on 2023-06-11 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0031_alter_student_active_alter_student_registered'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Active',
            new_name='active_symbol',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Registered',
            new_name='registered_symbol',
        ),
    ]
