# Generated by Django 4.2 on 2023-06-11 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0032_rename_active_student_active_symbol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='active_symbol',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='registered_symbol',
            field=models.BooleanField(default=False),
        ),
    ]
