# Generated by Django 4.2 on 2023-06-11 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0033_alter_student_active_symbol_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_date', models.DateField()),
                ('installment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='active_symbol',
        ),
        migrations.RemoveField(
            model_name='student',
            name='registered_symbol',
        ),
        migrations.DeleteModel(
            name='FeeDetails',
        ),
    ]
