# Generated by Django 4.2 on 2023-06-11 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0034_installment_remove_student_active_symbol_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selection_type', models.CharField(choices=[('one_times', 'One Time'), ('two_times', 'Two Times'), ('three_times', 'Three Times')], max_length=20, null=True)),
                ('first_pay', models.DateField(blank=True, null=True)),
                ('first_pay_amount', models.IntegerField(blank=True, null=True)),
                ('second_pay', models.DateField(blank=True, null=True)),
                ('second_pay_amount', models.IntegerField(blank=True, null=True)),
                ('third_pay', models.DateField(blank=True, null=True)),
                ('third_pay_amount', models.IntegerField(blank=True, null=True)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.student')),
            ],
        ),
        migrations.DeleteModel(
            name='Installment',
        ),
    ]
